### ISSUE TITLE
Hayashi doesn;t always need to clone the repo

### ISSUE THREAD

**Issue by comfysage** [comfysage/hayashi#3]
Sometimes (like with vim-plug, ohmyzsh) hayashi doesn't need to clone the repo in order to run the installer.

Proposed option (`true` by default):
```yaml
pkg: name
url: github.com/owner/repo
clone: false
```
