### ISSUE TITLE
pack using symlink instead of installing

### ISSUE THREAD

**Issue by comfysage** [comfysage/hayashi#4]
Hayashi currently installs binaries and man files using `install`.
This is mostly usefull when repos won't always be available or `hayashi tidy` (not implemented yet) is used.

In some cases using symlinks instead might be more usefull.

Proposed feature (`false` by default):
```yaml
pack:
  - path: path/to/file
    type: type
    symlink: true
```

This would use
```shell
ln -s $(repo_dir)/path/to/file ~/.hayashi/pack/type/
```
instead of
```shell
install $(repo_dir)/path/to/file ~/.hayashi/pack/type/
```
